### ISSUE TITLE
Add all contributors to the readme file

### ISSUE THREAD

**Issue by TheLunchtimeAttack** [TheLunchtimeAttack/matasano-challenges#3]
First task is to get everyone to test out pull requests to add themselves to the [readme](../blob/master/README.md).

Come find me (Sam) if you have any problems.

**Comment by samscott89** [comment]
Ok, some tips for completing this:

1. Create a new branch (locally) for making your changes:
    git checkout -b add-name
2. Make the changes to the `README.md` file (note: you need 2 spaces at the end of the line for a newline).
3. Commit these changes and push to your fork (still in a new branch).
```
git add -u # This adds changes to all tracked file
git commit # Add a nice commit message, and then close nano
git push --set-upstream origin add-name # Creates a new branch on your github fork to push to

```
We'll cover these commands, particularly the last one, next week.
4. Create your pull request!
Go the [repo page](../) and click "New pull request". Make sure the `compare:` branch is the one you've made the changes to. And create your pull request!
5. Wait for feedback.

Hope that helps.

P.S. For extra marks, make sure you get the most up-to-date version of the repo before branching/making changes:
```
git remote add
```

**Comment by samscott89** [comment]
Some other nice info:  [Markdown basics](https://help.github.com/articles/markdown-basics/).

Github uses Markdown for rendering text/comments etc.

**Comment by RPL226** [comment]
The commands you give in the PS aren't correct.  The second should be

`git remote add upstream git@github.com:The LunchtimeAttack/matasano-challenges.git`

**Comment by TheLunchtimeAttack** [comment]
Thanks. Not sure anyone reads this anyway :)

**Comment by BenC7** [comment]
We do! Eventually...

**Comment by gchers** [comment]
Should be closed? If so, I'll add a "Closes" keyword [1] to my last pull request, so when you accept it this Issue should be marked as closed.

Refs
[1] https://help.github.com/articles/closing-issues-via-commit-messages/
