### ISSUE TITLE
Bytestring vs lists

### ISSUE THREAD

**Issue by TheLunchtimeAttack** [TheLunchtimeAttack/matasano-challenges#37]
Which one is better to use? 

Discuss...

**Comment by gchers** [comment]
It is quite common in Python to represent a string of bytes as a string object, in which each character represents one byte. For example, the string of bytes:
```
0xcc0bfa41
```
can be represented as:
```
'\xcc\x0b\xfaA'
```
You can see that '\xcc' represents the byte 0xcc, and so on.
Notice that the byte 0x41 is converted to its ASCII value 'A' [1].

This convention is quite handy, and many libraries adopt it.
For example, see pycrypto [2] and scapy [3,4].

The library *binascii* [5] allows to easily move from a string of hexadecimal values to its binary form:
```
import binascii
hex_representation = 'cc0bfa41'
bin_representation = binascii.unhexlify(hex_representation)
```
bin_representation takes value '\xcc\x0b\xfaA'.

Advantages of using this convention: i) commonly used, ii) many libraries support it directly, iii) there are tools (binascii) to make its use painless.

References
[1] http://www.asciitable.com/.
[2] http://docs.python-guide.org/en/latest/scenarios/crypto/.
[3] http://www.secdev.org/projects/scapy/.
[4] http://www.secdev.org/projects/scapy/doc/usage.html.
[5] http://effbot.org/librarybook/binascii.htm.

**Comment by TheLunchtimeAttack** [comment]
@gchers please :smiley:

**Comment by gchers** [comment]
k den:)
